services:
  api:
    build: ./api
    ports:
      - "3003:3001"
    environment:
      - API_SECRET=hello-from-env

  frontend:
    build:
      context: ./frontend
      args:
        VITE_API_URL: "https://api.jaydenmistry.net"
    ports:
      - "3004:3000"
    environment:
      - VITE_API_URL=https://api.jaydenmistry.net
    depends_on:
      - api