services:
  api:
    build:
      context: ./api
    ports:
      - "3001:3001"
    environment:
      - API_SECRET=hello-from-env

  frontend:
    build:
      context: ./frontend
      args:
        CACHEBUST: ${CACHEBUST}
    ports:
      - "3002:3000"
    environment:
      - VITE_API_URL=https://api.jaydenmistry.net
    depends_on:
      - api